package dev.zeroday.health.metrics.model;

public enum MetricType {
    WEIGHT,
    BODY_FAT,
    BMI,
    SKELETAL_MUSCLE,
    MUSCLE_MASS,
    FAT_FREE_WEIGHT,
    BODY_WATER,
    BONE_MASS,
    PROTEIN_PCT,
    BMR,
    METABOLIC_AGE,
    SUBCUTANEOUS_FAT,
    VISCERAL_FAT,
    CHEST,
    SHOULDERS,
    LEFT_ARM,
    RIGHT_ARM,
    LEFT_WRIST,
    RIGHT_WRIST,
    NECK,
    WAIST,
    HIPS,
    ABDOMEN,
    LEFT_THIGH,
    RIGHT_THIGH,
    LEFT_CALF,
    RIGHT_CALF,
    FOREARM,
    WAIST_HIP_RATIO,
    CHEST_HIP_RATIO,
    WAIST_CHEST_RATIO,
    CUSTOM
}
