ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS activity_level VARCHAR(20) DEFAULT 'MODERATE';
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS diet_goal VARCHAR(20) DEFAULT 'MAINTAIN';

-- activity_level: SEDENTARY, LIGHT, MODERATE, ACTIVE, VERY_ACTIVE
-- diet_goal: CUT, MAINTAIN, BULK
